# This file stores all constant values.

PATH = {
    "weakly_supervised": {
        "path": "data/reports/extracted/"
    },
    "RAG": {
        "vector_index": "data/ifrs_enriched_Llama70B_NVEmbedV2",
        "prev_retrieved": "outputs/retrieved/",
        "post_retrieved": "outputs/postRAG/{0}_Llama-3.1-70B-Instruct/"
    },
    "LLM": {
        "examples": "data/few_shot_examples.json"
    },
    "TAX": "data/ifrs_sds_taxonomy_enriched_Llama-3.1-70B-Instruct.json", # taxonomy_enriched-Llama70B
    "KG": "outputs/graph/"
}

LABELS_DICT = {
    "entities": [
        "organization",
        "sustainability report",
        "business model",
        "governance",
        "strategy",
        "risk",
        "opportunity",
        "target",
        "disclosure standard",
        "disclosure topic"
    ],
    "relations": [
        "ComparedTo",
        "Outputs",
        "RunBy",
        "ProvidedBy",
        "ValidatedBy",
        "UsedIn",
        "MeasuredAt",
        "MountedOn",
        "TargetsLocation",
    ],
    "label_mapper": {
        "Organizations": "organization",
        "Sustainability reports": "sustainability report",
        "Disclosure report": "sustainability report",
        "Climate disclosure report": "sustainability report",
        "Financial report": "sustainability report",
        "GOVERNANCE": "governance",
        "STRATEGY": "strategy",
        "Climate risks": "risk",
        "RISKS": "risk",
        "Climate opportunity": "opportunity",
        "OPPORTUNITY": "opportunity",
        "Climate targets": "target",
        "Climate goals": "target",
        "Sustainability targets": "target",
        "Sustainability goals": "target",
        "METRICS AND TARGETS": "target",
        "Reporting standard": "disclosure standard",
        "Reporting topic": "disclosure topic"
    },
}
text_template = "<heading>{}</heading>\n{}\n"

REPORTS = [
    "2022 Microsoft Environmental Sustainability Report",
    "2022_BXP_ESG_Report",
    "2023 Lloyds sustainability report",
    "AEO 2022 ESG Report",
    "AstraZeneca Sustainability Report 2023",
    "AT&T 2022 Sustainability Summary",
    "Boeing 2023 Sustainability Report",
    "CostCo Climate Action Plan",
    # "Coca-Cola Business Sustainability Report 2022",
    "CT REIT 2022 ESG Report",
    "Deloitte 2023 Global Impact Report",
    "HM Group Sustainability Disclosure 2022",
    "HSBC Annual Holdings and Accounts Report 2023",
    "JP Morgan Climate Report 2022",
    "Mastercard 2022 ESG Report",
    "McKinsey 2022 ESG Full Report",
    "Meta 2023 Sustainability Report",
    "Microsoft 2022 Environmental Sustainability Report",
    "Netflix ESG Report 2022",
    "New Look sustainability report",
    "PayPal Global Impact Report 2023",
    "Qantas 2023 Sustainability Report",
    "Rio Tinto Climate Change Report 2023",
    "Ryanair 2022 Sustainability Report",
    "Sony Sustainability Report 2023",
    "Starbucks Environmental & Social Impact Report 2022",
    "Suncor Sustainability Report 2023",
    "University of Oxford 2022 Sustainability Report",
    "Veolia ESG Report 2023",
    "Walmart ESG Highlights 2023",
    "Westpac 2023 climate report",
    "Woolworths Group 2023 Sustainability Report"
]

QUESTIONS = [
    "Do the environmental/sustainability targets set by the company align with external climate change adaptation goals/targets?",
    "Do the environmental/sustainability targets set by the company reference external climate change adaptation goals/targets?",
    "Does the company identify any impacts of its business activities on the environment?",
    "Does the company have a strategy on waste management?",
    "Does the company report short-term actions taken or planned to reduce its waste generation?",
    "Does the company report a plan to engage with downstream partners on water consumption or water pollution?",
    "Does the company encourage downstream partners to carry out climate-related risk assessments?",
    "Does the company have a specific process in place to identify risks arising from climate change?",
    "Does the company refer to any third party scenarios when identifying climate-related risks or opportunities (e.g. IPCC trajectories, NGFS scenarios, etc.)?",
    "Does the company report how adjustments to its business operations will allow it to adapt to climate change?",
    "Does the company report the methodology used to identify the dependencies and impact of its business activities on the environment?",
    "Does the company report the climate change scenarios used to test the resilience of its business strategy?",
    "Has the company identified any synergies between its climate change adaptation goals and other business goals?",
    "Does the company seek to adjust its business model to better provide climate change adaptation products and services?",
    "Does the company provide definitions for climate change adaptation?"
    ]

SKIP_WORDS = [
            "the",
            "this",
            "these",
            "those",
            "that",
            "one",
            "two",
            "a",
            "an",
            "his",
            "her",
            "many",
            "they",
            "their",
            "et al",
            "some",
            "such",
            "its",
            "all",
            "each",
            "both",
            "our",
            "we",
            "us",
            "our",
            "you",
            "your",
            "my",
            "mine",
            "he",
            "she",
            "it",
            "I",
            "me",
            "who",
            "whom",
            "whose",
            "which",
            "what",
            "any",
            "few",
            "several",
            "more",
            "most",
            "other",
            "another",
            "much",
            "him",
            "hers",
            "ours",
            "yours",
            "theirs",
            "there",
            "here",
            "and",
            "or",
            "nor",
            "but",
            "if",
            "while",
            "because",
            "to",
            "from",
            "of",
            "for",
            "with",
            "on",
            "at",
            "by",
            "about",
            "as",
            "in",
            "into",
            "upon",
            "like",
            "through",
            "over",
            "under",
            "between",
            "since",
            "until",
            "dataset",
        ]

SKIP_CHARS = [
            ".",
            "/",
            "%",
            "(",
            "fig",
            "table",
        ]

DELIMITERS = {
    "section_delimiter": "-",
    "tuple_delimiter": "<|>",
    "completion_delimiter": "<|COMPLETE|>",
    "record_delimiter": "##",
}

ABBREVIATIONS = {
    'ghg': 'greenhouse gases',
    'co2': 'carbon dioxide',
    'co2e': 'carbon dioxide equivalent',
    'mtco2e': 'metric tons carbon dioxide equivalent',
    'mtcoze': 'metric tons carbon dioxide equivalent',
    'mwh': 'megawatt-hour',
    'kwh': 'kilowatt-hour',
    'ch4': 'methane',
    'n2o': 'nitrous oxide',
    'esg': 'environmental social governance',
    'ifrs': 'international financial reporting standards',
    'tcfd': 'task force on climate related financial disclosures',
    'sasb': 'sustainability accounting standards board',
    'esrs': 'european sustainability reporting standard',
    'cdp': 'carbon disclosure project',
    'sbti': 'science based targets initiative',
    'gri': 'global reporting initiative',
    'cop26': '26th united nations climate change conference',
    'un': 'united nations',
    'eu': 'european union',
    'us': 'united states of america',
    'epa': 'environment protection agency',
    'defra': 'department for environment, food and rural affairs',
    'ceo': 'chief executive officer',
    'cfo': 'chief financial officer',
    'ev': 'electical vehicle',
    'evs': 'electrical vehicle',
    'ngo': 'non governmental organization',
    'erm': 'enterprise risk management',
    'saf': 'sustainable aviation fuel',
    'ipcc': 'intergovernmental panel on climate change',
    'recs': 'renewable energy certificates',
    'ppas': 'power purchase agreements',
    'pue': 'power usage effectiveness',
    'aws': 'amazon web services'
}   

ORG_SUFFIXES = {
    'inc', 'incorporated', 'corp', 'corporation', 'ltd', 'limited',
    'llc', 'co', 'company', 'plc', 'gmbh', 'ag', 'sa', 'nv'
}