PATH = {
    "weakly_supervised": {
        "text": "../ClimateIE/parsed_text",
        "path": "././data/reports/processed/",
        "RAG_preprocessed": "././outputs/preRAG",
    },
    "RAG": {
        "vector_index": "././data/ifrs_enriched_Llama70B_NVEmbedV2",
        "prev_retrieved": "././outputs/retrieved",
    },
    "LLM": {
        "examples": "././outputs/few_shot.json",
        "chunked_text": "././outputs/chunked_text_600tokens",
    },
    "TAX": "././data/ifrs_taxonomy_enriched-Llama70B.json",
}


LABELS_DICT = {
    "entities": [
        "organization",
        "sustainability report",
        "business model",
        "governance",
        "strategy",
        "risk",
        "opportunity",
        "target",
        "disclosure standard",
        "disclosure topic"
    ],
    "relations": [
        "ComparedTo",
        "Outputs",
        "RunBy",
        "ProvidedBy",
        "ValidatedBy",
        "UsedIn",
        "MeasuredAt",
        "MountedOn",
        "TargetsLocation",
    ],
    "label_mapper": {
        "Organizations": "organization",
        "Sustainability reports": "sustainability report",
        "Disclosure report": "sustainability report",
        "Climate disclosure report": "sustainability report",
        "Financial report": "sustainability report",
        "GOVERNANCE": "governance",
        "STRATEGY": "strategy",
        "Climate risks": "risk",
        "RISKS": "risk",
        "Climate opportunity": "opportunity",
        "OPPORTUNITY": "opportunity",
        "Climate targets": "target",
        "Climate goals": "target",
        "Sustainability targets": "target",
        "Sustainability goals": "target",
        "METRICS AND TARGETS": "target",
        "Reporting standard": "disclosure standard",
        "Reporting topic": "disclosure topic"
    },
}
text_template = "<heading>{}</heading>\n{}\n"


REPORTS = [
    "2022 Microsoft Environmental Sustainability Report",
    "AstraZeneca Sustainability Report 2023",
    "2023 Lloyds sustainability report",
    "AEO 2022 ESG Report",
    "AT&T 2022 Sustainability Summary",
    "Boeing 2023 Sustainability Report",
    "Coca-Cola Business Sustainability Report 2022",
    "CT REIT 2022 ESG Report",
    "Deloitte 2023 Global Impact Report",
    "HM Group Sustainability Disclosure 2022",
    "HSBC Annual Holdings and Accounts Report 2023",
    "JP Morgan Climate Report 2022",
    "Mastercard 2022 ESG Report",
    "McKinsey 2022 ESG Full Report",
    "Meta 2023 Sustainability Report",
    "Netflix ESG Report 2022",
    "New Look sustainability report",
    "PayPal Global Impact Report 2023",
    "Qantas 2023 Sustainability Report",
    "Rio Tinto Climate Change Report 2023",
    "Ryanair 2022 Sustainability Report",
    "Sony Sustainability Report 2023",
    "Starbucks Environmental & Social Impact Report 2022",
    "Suncor Sustainability Report 2023",
    "University of Oxford 2022 Sustainability Report",
    "Veolia ESG Report 2023",
    "Walmart ESG Highlights 2023",
    "Westpac 2023 climate report",
    "Woolworths Group 2023 Sustainability Report"
]

SKIP_WORDS = [
            "the",
            "this",
            "these",
            "those",
            "that",
            "one",
            "two",
            "a",
            "an",
            "his",
            "her",
            "many",
            "they",
            "their",
            "et al",
            "some",
            "such",
            "its",
            "all",
            "each",
            "both",
            "our",
            "we",
            "us",
            "our",
            "you",
            "your",
            "my",
            "mine",
            "he",
            "she",
            "it",
            "I",
            "me",
            "who",
            "whom",
            "whose",
            "which",
            "what",
            "any",
            "few",
            "several",
            "more",
            "most",
            "other",
            "another",
            "much",
            "him",
            "hers",
            "ours",
            "yours",
            "theirs",
            "there",
            "here",
            "and",
            "or",
            "nor",
            "but",
            "if",
            "while",
            "because",
            "to",
            "from",
            "of",
            "for",
            "with",
            "on",
            "at",
            "by",
            "about",
            "as",
            "in",
            "into",
            "upon",
            "like",
            "through",
            "over",
            "under",
            "between",
            "since",
            "until",
            "dataset",
        ]

SKIP_CHARS = [
            ".",
            "/",
            "%",
            "(",
            "fig",
            "table",
        ]